### ISSUE TITLE
同步时会完成当前全部土豆，造成土豆完成数量巨大

### ISSUE THREAD

**Issue by Sendarg** [jinntrance/pomodoit#12]
如题。

**Comment by jinntrance** [comment]
多谢反馈。但你的问题我没办法重现。

劳烦你再帮着check 一下如下几个问题：

1. 当前全部土豆的名称，是不是之前在Doit.im 里面出现过然后被标记完成了？
2. 劳烦在Chrome 浏览器输入`chrome://extensions/` 找到Pomodoit, 然后点击`background page` 并切换到`Console`;这样重新点击右上角的图标同步，看如果有报错，麻烦截图附上。
