### ISSUE TITLE
按照操作各种试，似乎用不了，这个还更新吗？

### ISSUE THREAD

**Issue by bandaot** [jinntrance/pomodoit#13]
这个应用很有用，希望能够继续维护，谢谢！

**Comment by jinntrance** [comment]
我这面一直在用。是可以从doit 网站同步到Pomotodo 上的。 

正常情况下会提示登录doit.im和Pomotodo 网站，然后就能定时或手动（点击Chrome 右上角的icon）把doit Today 里的tasks 同步到Pomotodo 上。

您能描述更多的您的操作步骤么？

**Comment by bandaot** [comment]
common.js:179 GET https://pomotodo.com//api/pomo?days=1&_=1467704800123 503 (Service Temporarily Unavailable)
一直都是这个没法获取，api真的能用么？

**Comment by jinntrance** [comment]
再看了看，现在测试确实没办法同步了。pomotodo 的接口改版了（https://api-ng.pomotodo.com/account/sync
）。回头周末弄着更新一下。

On Tue, 5 Jul 2016 at 15:50 bandaot <notifications@github.com> wrote:

> common.js:179 GET https://pomotodo.com//api/pomo?days=1&_=1467704800123
> 503 (Service Temporarily Unavailable)
> 一直都是这个没法获取，api真的能用么？
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/jinntrance/pomodoit/issues/13#issuecomment-230409732>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACTYRHj_rVmHHBa47HcNztMytdivs48Uks5qSgy1gaJpZM4IaxQs>
> .
>
-- 
Best regards,
Joseph Jin-Chuan Tang

**Comment by bandaot** [comment]
谢啦

**Comment by jinntrance** [comment]
@bandaot 你如果有时间改再提PR 自然更好，我这面也可以提供协助。

**Comment by tttwwy** [comment]
请问是否有更新？现在仍然无法正常同步，非常 感谢

**Comment by jinntrance** [comment]
@tttwwy @bandaot 抱歉。

本来想停掉这个项目的，不料还有用户在用。2015 年下半年Doit.im 停止更新后，当时用这个插件的用户变少了，我也改用Todoist 了。

我粗看了一下，pomotodo 变成了新的认证方式，fix 会有不少修改。由于我个人精力有限，目前还不能确定明确的修复时间。

**Comment by jinntrance** [comment]
升级后已经可以同步了，不过目前Pomotodo API 限制，Pro 用户才能享受同步功能了。

**Comment by tttwwy** [comment]
@jinntrance ,非常感谢，我去充个Pro会员好了。
